import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'de' | 'en';

type Replacements = Record<string, string | number>;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, replacements?: Replacements) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  de: {
    'nav.home': 'Startseite',
    'nav.venues': 'Locations',
    'nav.services': 'Dienstleistungen',
    'nav.request': 'Anfrage',
    'nav.login': 'Login',
    'nav.signup': 'Registrieren',
    'nav.booking': 'Jetzt buchen',
    'nav.account': 'Mein Konto',
    'nav.backHome': 'Zur Startseite',
    'nav.logout': 'Logout',
    'footer.copy': '© {year} EventVenue. Alle Rechte vorbehalten.',
    'footer.impressum': 'Impressum',
    'footer.privacy': 'Datenschutz',
    'footer.terms': 'AGB',
    'footer.vendorTerms': 'Vendor-Bedingungen',
    'footer.refunds': 'Storno & Erstattung',
    'footer.contact': 'Kontakt',
    'footer.cookies': 'Cookies',

    'home.hero.title': 'Buche die perfekte Event-Location',
    'home.hero.subtitle': 'Finde die ideale Location und passende Services fuer deinen besonderen Anlass.',
    'home.hero.cta': 'Locations ansehen',
    'home.hero.dashboard': 'Zum Dashboard',
    'home.hero.vendorStart': 'Als Vendor starten',
    'home.categories.title': 'Kategorien entdecken',
    'home.categories.subtitle': 'Finde passende Profis fuer Musik, Catering, Dekoration und mehr.',
    'home.categories.dj': 'DJs & Musik',
    'home.categories.photo': 'Fotografie',
    'home.categories.catering': 'Catering',
    'home.categories.decoration': 'Dekoration',
    'home.categories.vendors': '{count}+ Anbieter',
    'home.why.title': 'Warum EventVenue',
    'home.why.curated.title': 'Gepruefte Vendor',
    'home.why.curated.desc': 'Jeder Vendor wird vor Freigabe geprueft, damit die Qualitaet stabil bleibt.',
    'home.why.secure.title': 'Sichere Zahlungen',
    'home.why.secure.desc': 'Zahlungen laufen ueber Stripe mit klarer Transaktionshistorie.',
    'home.why.booking.title': 'Strukturierte Buchung',
    'home.why.booking.desc': 'Angebote verhandeln und erst nach finaler Einigung zahlen.',
    'home.services.title': 'Komplette Event-Loesungen',
    'home.services.venues': 'Premium Locations',
    'home.services.venues.desc': 'Waehle aus beeindruckenden Veranstaltungsorten',
    'home.services.djs': 'Professionelle DJs',
    'home.services.djs.desc': 'Sorge fuer Stimmung die ganze Nacht',
    'home.services.catering': 'Catering Services',
    'home.services.catering.desc': 'Leckeres Essen fuer jeden Geschmack',
    'home.services.makeup': 'Make-up und Dekor',
    'home.services.makeup.desc': 'Styling- und Dekorationsservices aus einer Hand',
    'home.services.photography': 'Fotografie',
    'home.services.photography.desc': 'Halte jeden besonderen Moment fest',
    'home.featured.title': 'Empfohlene Locations',
    'home.featured.viewAll': 'Alle ansehen',
    'home.cta.title': 'Bereit fuer dein Event?',
    'home.cta.subtitle': 'Plane dein Event heute: Locations waehlen, Services buchen, alles an einem Ort.',
    'home.cta.button': 'Buchung starten',
    'home.cta.request': 'Anfrage erstellen',

    'venues.title': 'Verfuegbare Locations',
    'venues.subtitle': 'Entdecke unsere Premium Event-Locations',
    'venues.filters': 'Filter',
    'venues.filter.searchLabel': 'Suche',
    'venues.filter.search': 'Locations suchen...',
    'venues.filter.type': 'Location-Typ',
    'venues.filter.all': 'Alle Locations',
    'venues.filter.capacityPlaceholder': 'z. B. 100',
    'venues.capacity': 'Kapazitaet',
    'venues.location': 'Ort',
    'venues.viewDetails': 'Details ansehen',
    'venues.resultsFound.one': '{count} Location gefunden',
    'venues.resultsFound.other': '{count} Locations gefunden',
    'venues.notFound': 'Keine Locations gefunden',
    'venues.notFound.desc': 'Passe deine Suche oder Filter an',
    'services.title': 'Dienstleistungen',
    'services.subtitle': 'Einzelne Dienstleistungen fuer dein Event entdecken und buchen',
    'services.tabs.all': 'Alle Dienstleistungen',
    'services.tabs.dj': 'DJ-Services',
    'services.tabs.catering': 'Catering',
    'services.tabs.makeup': 'Make-up Artists',
    'services.tabs.decorations': 'Dekoration',
    'services.tabs.photography': 'Fotografie',
    'services.search.placeholder': 'Suchen...',
    'services.filter.button': 'Filter',
    'services.filter.show': 'Filter anzeigen',
    'services.filter.hide': 'Filter ausblenden',
    'services.filter.rating': 'Mindestbewertung',
    'services.filter.maxPrice': 'Max Preis: EUR {price}',
    'services.filter.sortBy': 'Sortieren nach',
    'services.rating.all': 'Alle Bewertungen',
    'services.rating.stars': 'Sterne',
    'services.sort.highestRated': 'Hoechste Bewertung',
    'services.sort.lowestPrice': 'Niedrigster Preis',
    'services.sort.highestPrice': 'Hoechster Preis',
    'services.results.showing': '{count} Serviceanbieter',
    'services.results.empty': 'Keine Serviceanbieter gefunden. Bitte Filter anpassen.',
    'services.card.detailsButton': 'Details',
    'services.card.offerButton': 'Angebot',
    'services.dialog.title': 'Anbieterdetails',
    'services.dialog.offerTitle': 'Kurzes Angebot senden',
    'services.dialog.description': '{provider} fuer {service}',
    'services.dialog.basePrice': 'Basispreis',
    'services.dialog.rating': 'Bewertung',
    'services.dialog.specialties': 'Spezialisierungen',
    'services.dialog.offerLabel': 'Dein Angebot (EUR)',
    'services.dialog.form.name': 'Name',
    'services.dialog.form.email': 'E-Mail',
    'services.dialog.form.phone': 'Telefon',
    'services.dialog.form.date': 'Event-Datum',
    'services.dialog.form.guests': 'Anzahl Gaeste',
    'services.dialog.form.message': 'Kurzinfo (optional)',
    'services.dialog.form.messagePlaceholder': 'z. B. Aufbau ab 16:00',
    'services.dialog.submitOffer': 'Angebot senden',
    'services.dialog.offerSent': 'Angebot gesendet. Der Anbieter kann annehmen, ablehnen oder ein Gegenangebot machen.',

    'venue.notFound.title': 'Location nicht gefunden',
    'venue.back': 'Zurueck zu den Locations',
    'venue.perEvent': 'pro Event',
    'venue.features': 'Ausstattung',
    'venue.guests': 'Bis zu {count} Gaeste',
    'venue.eventDate': 'Event-Datum',
    'venue.selectDate': 'Event-Datum auswaehlen',
    'venue.dateConfirmed': 'Datum bestaetigt: {date}',
    'venue.selectDate.desc': 'Waehle dein Wunschdatum und pruefe die Verfuegbarkeit.',
    'venue.notAvailable': 'Location nicht verfuegbar',
    'venue.notAvailable.desc': 'Die Location ist an diesem Datum bereits gebucht.',
    'venue.available': 'Location verfuegbar',
    'venue.available.desc': 'Die Location ist an diesem Datum verfuegbar.',
    'venue.calendar.available': 'Verfuegbar',
    'venue.calendar.booked': 'Belegt',
    'venue.calendar.hint': 'Zum Oeffnen auf das Datumsfeld klicken',
    'venue.services.title': 'Serviceanbieter auswaehlen',
    'venue.services.desc': 'Waehle aus professionellen Serviceanbietern. Grau markierte Anbieter sind an diesem Datum belegt.',
    'venue.summary.title': 'Geschaetzte Gesamtsumme',
    'venue.summary.services': 'Location + {count} Service(s)',
    'venue.summary.note': '*Endpreis wird anhand der Gaestezahl berechnet',
    'venue.summary.proceed': 'Buchung abschliessen',
    'venue.booked': 'Belegt',
    'venue.reviews': 'Bewertungen',
    'venue.perPerson': '/Person',
    'venue.alert.selectDate': 'Bitte ein Event-Datum auswaehlen',
    'venue.alert.notAvailable': 'Diese Location ist am gewaehlten Datum nicht verfuegbar',

    'booking.title': 'Buchung abschliessen',
    'booking.subtitle': 'Trage deine Daten ein, um die Buchung zu bestaetigen',
    'booking.info.title': 'Deine Angaben',
    'booking.info.name': 'Vollstaendiger Name',
    'booking.info.email': 'E-Mail',
    'booking.info.phone': 'Telefonnummer',
    'booking.info.altName': 'Alternative Kontaktperson',
    'booking.info.altPhone': 'Alternative Telefonnummer',
    'booking.info.contactMethod': 'Bevorzugte Kontaktmethode',
    'booking.info.contactMethod.email': 'E-Mail',
    'booking.info.contactMethod.phone': 'Telefon',
    'booking.info.contactMethod.whatsapp': 'WhatsApp',
    'booking.info.time': 'Event-Uhrzeit',
    'booking.info.setupTime': 'Aufbau-Beginn (optional)',
    'booking.info.type': 'Event-Typ',
    'booking.info.guests': 'Anzahl Gaeste',
    'booking.info.address': 'Event-Adresse',
    'booking.info.city': 'Stadt',
    'booking.info.postalCode': 'Postleitzahl',
    'booking.info.notes': 'Zusaetzliche Hinweise',
    'booking.info.notes.placeholder': 'Besondere Anforderungen oder Fragen?',
    'booking.info.maxCapacity': 'Maximale Kapazitaet: {count} Gaeste',
    'booking.type.select': 'Typ auswaehlen',
    'booking.type.wedding': 'Hochzeit',
    'booking.type.corporate': 'Firmenevent',
    'booking.type.birthday': 'Geburtstagsfeier',
    'booking.type.conference': 'Konferenz',
    'booking.type.other': 'Sonstiges',
    'booking.submit': 'Anfrage senden',
    'booking.review.notice': 'Hinweis: Endpreis kann sich nach Anbieterpruefung (z. B. Anfahrt/Distanz) aendern.',
    'booking.review.approval': 'Ich akzeptiere, dass der Anbieter die Anfrage annehmen/ablehnen und den Preis anpassen kann.',
    'booking.summary.title': 'Buchungsuebersicht',
    'booking.summary.eventDate': 'Event-Datum',
    'booking.summary.venue': 'Location',
    'booking.summary.services': 'Ausgewaehlte Services',
    'booking.summary.rating': 'Bewertung',
    'booking.summary.subtotal': 'Zwischensumme',
    'booking.summary.fee': 'Servicegebuehr (10%)',
    'booking.summary.total': 'Gesamt',
    'booking.summary.forGuests': 'Fuer {count} Gaeste',
    'booking.summary.enterGuests': 'Gaestezahl eingeben, um den Endpreis zu sehen',
    'booking.summary.noData': 'Keine Buchungsdaten gefunden',
    'booking.summary.browse': 'Locations ansehen',
    'booking.success.title': 'Anfrage gesendet',
    'booking.success.message': 'Danke. Deine Anfrage wurde an den Anbieter gesendet und wartet auf Annahme oder Ablehnung.',
    'booking.success.status': 'Status: Wartet auf Anbieterantwort',
    'booking.success.eventDate': 'Event-Datum',
    'booking.success.eventTime': 'Event-Uhrzeit',
    'booking.success.redirecting': 'Weiterleitung zur Startseite...',

    'notFound.page': 'Seite nicht gefunden',
    'notFound.backHome': 'Zurueck zur Startseite',
    'auth.name': 'Name',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.login.title': 'Login',
    'auth.login.subtitle': 'Melde dich an, um Anfragen zu verwalten',
    'auth.login.button': 'Einloggen',
    'auth.login.noAccount': 'Noch kein Konto?',
    'auth.signup.title': 'Sign up',
    'auth.signup.subtitle': 'Erstelle ein Konto fuer Angebote und Anfragen',
    'auth.signup.button': 'Konto erstellen',
    'auth.signup.hasAccount': 'Bereits ein Konto?',
    'cookies.banner.title': 'Cookie-Einstellungen',
    'cookies.banner.description': 'Wir verwenden notwendige Cookies fuer den Betrieb. Mit deiner Zustimmung nutzen wir zusaetzlich Analyse- und Marketing-Cookies.',
    'cookies.banner.accept': 'Alle akzeptieren',
    'cookies.banner.reject': 'Nicht notwendige ablehnen',
    'cookies.banner.customize': 'Anpassen',
    'cookies.banner.hideCustomize': 'Anpassung schliessen',
    'cookies.banner.saveSelection': 'Auswahl speichern',
    'cookies.banner.settings': 'Cookie-Seite',
    'cookies.settings.title': 'Cookie-Einstellungen',
    'cookies.settings.description': 'Passe hier jederzeit deine Cookie-Praeferenzen an.',
    'cookies.settings.alwaysOn': 'Notwendige Cookies sind immer aktiv.',
    'cookies.settings.save': 'Speichern',
    'cookies.settings.saved': 'Cookie-Auswahl gespeichert.',
    'cookies.settings.backHome': 'Zurueck zur Startseite',
    'cookies.category.necessary': 'Notwendig',
    'cookies.category.preferences': 'Praeferenzen',
    'cookies.category.analytics': 'Analyse',
    'cookies.category.marketing': 'Marketing'
  },
  en: {
    'nav.home': 'Home',
    'nav.venues': 'Venues',
    'nav.services': 'Services',
    'nav.request': 'Request',
    'nav.login': 'Login',
    'nav.signup': 'Sign Up',
    'nav.booking': 'Book Now',
    'nav.account': 'My Account',
    'nav.backHome': 'Back to Home',
    'nav.logout': 'Logout',
    'footer.copy': '© {year} EventVenue. All rights reserved.',
    'footer.impressum': 'Legal Notice',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.vendorTerms': 'Vendor Terms',
    'footer.refunds': 'Refund Policy',
    'footer.contact': 'Contact',
    'footer.cookies': 'Cookies',

    'home.hero.title': 'Book Your Perfect Event Venue',
    'home.hero.subtitle': 'Find the ideal venue and services for your special occasion.',
    'home.hero.cta': 'Explore Venues',
    'home.hero.dashboard': 'Open Dashboard',
    'home.hero.vendorStart': 'Start as Vendor',
    'home.categories.title': 'Explore Categories',
    'home.categories.subtitle': 'Find trusted professionals for music, catering, decoration, and more.',
    'home.categories.dj': 'DJs & Music',
    'home.categories.photo': 'Photography',
    'home.categories.catering': 'Catering',
    'home.categories.decoration': 'Decoration',
    'home.categories.vendors': '{count}+ vendors',
    'home.why.title': 'Why EventVenue',
    'home.why.curated.title': 'Curated Vendors',
    'home.why.curated.desc': 'Every vendor is reviewed before approval to keep quality high.',
    'home.why.secure.title': 'Secure Payments',
    'home.why.secure.desc': 'Payments run through Stripe with platform-first security.',
    'home.why.booking.title': 'Structured Booking',
    'home.why.booking.desc': 'Negotiate on-platform and pay only after final agreement.',
    'home.services.title': 'Complete Event Solutions',
    'home.services.venues': 'Premium Venues',
    'home.services.venues.desc': 'Choose from a variety of stunning locations',
    'home.services.djs': 'Professional DJs',
    'home.services.djs.desc': 'Keep your guests dancing all night long',
    'home.services.catering': 'Catering Services',
    'home.services.catering.desc': 'Delicious food for every taste',
    'home.services.makeup': 'Makeup and Decor',
    'home.services.makeup.desc': 'Complete styling and decoration services',
    'home.services.photography': 'Photography',
    'home.services.photography.desc': 'Capture every precious moment',
    'home.featured.title': 'Featured Venues',
    'home.featured.viewAll': 'View All',
    'home.cta.title': 'Ready to Book Your Event?',
    'home.cta.subtitle': 'Start planning your perfect event today.',
    'home.cta.button': 'Start Booking',
    'home.cta.request': 'Create Request',

    'venues.title': 'Available Venues',
    'venues.subtitle': 'Browse our collection of premium event venues',
    'venues.filters': 'Filters',
    'venues.filter.searchLabel': 'Search',
    'venues.filter.search': 'Search venues...',
    'venues.filter.type': 'Venue Type',
    'venues.filter.all': 'All Venues',
    'venues.filter.capacityPlaceholder': 'e.g., 100',
    'venues.capacity': 'Capacity',
    'venues.location': 'Location',
    'venues.viewDetails': 'View Details',
    'venues.resultsFound.one': '{count} venue found',
    'venues.resultsFound.other': '{count} venues found',
    'venues.notFound': 'No venues found',
    'venues.notFound.desc': 'Try adjusting your search or filters',
    'services.title': 'DJ Services',
    'services.subtitle': 'Browse and book individual services for your event',
    'services.tabs.all': 'All Services',
    'services.tabs.dj': 'DJ Services',
    'services.tabs.catering': 'Catering',
    'services.tabs.makeup': 'Makeup Artists',
    'services.tabs.decorations': 'Decoration',
    'services.tabs.photography': 'Photography',
    'services.search.placeholder': 'Search...',
    'services.filter.button': 'Filter',
    'services.filter.show': 'Show Filters',
    'services.filter.hide': 'Hide Filters',
    'services.filter.rating': 'Minimum Rating',
    'services.filter.maxPrice': 'Max Price: EUR {price}',
    'services.filter.sortBy': 'Sort By',
    'services.rating.all': 'All Ratings',
    'services.rating.stars': 'stars',
    'services.sort.highestRated': 'Highest Rated',
    'services.sort.lowestPrice': 'Lowest Price',
    'services.sort.highestPrice': 'Highest Price',
    'services.results.showing': 'Showing {count} service providers',
    'services.results.empty': 'No service providers found. Try adjusting your filters.',
    'services.card.detailsButton': 'Details',
    'services.card.offerButton': 'Offer',
    'services.dialog.title': 'Vendor Details',
    'services.dialog.offerTitle': 'Send Short Offer',
    'services.dialog.description': '{provider} for {service}',
    'services.dialog.basePrice': 'Base Price',
    'services.dialog.rating': 'Rating',
    'services.dialog.specialties': 'Specialties',
    'services.dialog.offerLabel': 'Your Offer (EUR)',
    'services.dialog.form.name': 'Name',
    'services.dialog.form.email': 'Email',
    'services.dialog.form.phone': 'Phone',
    'services.dialog.form.date': 'Event Date',
    'services.dialog.form.guests': 'Number of Guests',
    'services.dialog.form.message': 'Short Note (optional)',
    'services.dialog.form.messagePlaceholder': 'e.g. setup starts at 4 PM',
    'services.dialog.submitOffer': 'Send Offer',
    'services.dialog.offerSent': 'Offer sent. Vendor can accept, decline, or counter-offer.',

    'venue.notFound.title': 'Venue Not Found',
    'venue.back': 'Back to Venues',
    'venue.perEvent': 'per event',
    'venue.features': 'Features',
    'venue.guests': 'Up to {count} guests',
    'venue.eventDate': 'Event Date',
    'venue.selectDate': 'Select Event Date',
    'venue.dateConfirmed': 'Date confirmed: {date}',
    'venue.selectDate.desc': 'Choose your preferred date to check availability.',
    'venue.notAvailable': 'Venue Not Available',
    'venue.notAvailable.desc': 'This venue is already booked on this date.',
    'venue.available': 'Venue Available',
    'venue.available.desc': 'This venue is available on this date.',
    'venue.calendar.available': 'Available',
    'venue.calendar.booked': 'Booked',
    'venue.calendar.hint': 'Click the date field to open calendar',
    'venue.services.title': 'Select Service Providers',
    'venue.services.desc': 'Choose from our professional service providers.',
    'venue.summary.title': 'Estimated Total',
    'venue.summary.services': 'Venue + {count} service(s)',
    'venue.summary.note': '*Final price will be calculated based on number of guests',
    'venue.summary.proceed': 'Complete Booking',
    'venue.booked': 'Booked',
    'venue.reviews': 'reviews',
    'venue.perPerson': '/person',
    'venue.alert.selectDate': 'Please select an event date',
    'venue.alert.notAvailable': 'This venue is not available on the selected date',

    'booking.title': 'Complete Your Booking',
    'booking.subtitle': 'Fill in your details to confirm your event booking',
    'booking.info.title': 'Your Information',
    'booking.info.name': 'Full Name',
    'booking.info.email': 'Email',
    'booking.info.phone': 'Phone Number',
    'booking.info.altName': 'Alternate Contact Name',
    'booking.info.altPhone': 'Alternate Contact Phone',
    'booking.info.contactMethod': 'Preferred Contact Method',
    'booking.info.contactMethod.email': 'Email',
    'booking.info.contactMethod.phone': 'Phone',
    'booking.info.contactMethod.whatsapp': 'WhatsApp',
    'booking.info.time': 'Event Time',
    'booking.info.setupTime': 'Setup Start Time (optional)',
    'booking.info.type': 'Event Type',
    'booking.info.guests': 'Number of Guests',
    'booking.info.address': 'Event Address',
    'booking.info.city': 'City',
    'booking.info.postalCode': 'Postal Code',
    'booking.info.notes': 'Additional Notes',
    'booking.info.notes.placeholder': 'Any special requirements or questions?',
    'booking.info.maxCapacity': 'Maximum capacity: {count} guests',
    'booking.type.select': 'Select type',
    'booking.type.wedding': 'Wedding',
    'booking.type.corporate': 'Corporate Event',
    'booking.type.birthday': 'Birthday Party',
    'booking.type.conference': 'Conference',
    'booking.type.other': 'Other',
    'booking.submit': 'Send Request',
    'booking.review.notice': 'Note: Final price may change after vendor review (for example travel distance).',
    'booking.review.approval': 'I accept that the vendor can accept/decline this request and adjust pricing.',
    'booking.summary.title': 'Booking Summary',
    'booking.summary.eventDate': 'Event Date',
    'booking.summary.venue': 'Venue',
    'booking.summary.services': 'Selected Services',
    'booking.summary.rating': 'Rating',
    'booking.summary.subtotal': 'Subtotal',
    'booking.summary.fee': 'Service Fee (10%)',
    'booking.summary.total': 'Total',
    'booking.summary.forGuests': 'For {count} guests',
    'booking.summary.enterGuests': 'Enter number of guests to see final total',
    'booking.summary.noData': 'No booking data found',
    'booking.summary.browse': 'Browse Venues',
    'booking.success.title': 'Request Sent',
    'booking.success.message': 'Thanks. Your request was sent to the vendor and is pending approval or decline.',
    'booking.success.status': 'Status: Waiting for vendor response',
    'booking.success.eventDate': 'Event Date',
    'booking.success.eventTime': 'Event Time',
    'booking.success.redirecting': 'Redirecting to homepage...',

    'notFound.page': 'Page not found',
    'notFound.backHome': 'Back to Home',
    'auth.name': 'Name',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.login.title': 'Login',
    'auth.login.subtitle': 'Sign in to manage your requests',
    'auth.login.button': 'Login',
    'auth.login.noAccount': "Don't have an account?",
    'auth.signup.title': 'Sign Up',
    'auth.signup.subtitle': 'Create an account for offers and requests',
    'auth.signup.button': 'Create Account',
    'auth.signup.hasAccount': 'Already have an account?',
    'cookies.banner.title': 'Cookie Settings',
    'cookies.banner.description': 'We use necessary cookies to run this site. With your consent, we also use analytics and marketing cookies.',
    'cookies.banner.accept': 'Accept all',
    'cookies.banner.reject': 'Reject non-essential',
    'cookies.banner.customize': 'Customize',
    'cookies.banner.hideCustomize': 'Close customize',
    'cookies.banner.saveSelection': 'Save selection',
    'cookies.banner.settings': 'Cookie page',
    'cookies.settings.title': 'Cookie Settings',
    'cookies.settings.description': 'You can update your cookie preferences here at any time.',
    'cookies.settings.alwaysOn': 'Necessary cookies are always on.',
    'cookies.settings.save': 'Save',
    'cookies.settings.saved': 'Cookie settings saved.',
    'cookies.settings.backHome': 'Back to home',
    'cookies.category.necessary': 'Necessary',
    'cookies.category.preferences': 'Preferences',
    'cookies.category.analytics': 'Analytics',
    'cookies.category.marketing': 'Marketing'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('de');

  const t = (key: string, replacements?: Replacements) => {
    let text = translations[language][key] || translations.en[key] || key;

    if (replacements) {
      Object.entries(replacements).forEach(([placeholder, value]) => {
        text = text.replace(`{${placeholder}}`, String(value));
      });
    }

    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: 'de' as Language,
      setLanguage: () => {},
      t: (key: string, replacements?: Replacements) => {
        let text = translations.de[key] || translations.en[key] || key;
        if (replacements) {
          Object.entries(replacements).forEach(([placeholder, value]) => {
            text = text.replace(`{${placeholder}}`, String(value));
          });
        }
        return text;
      },
    };
  }
  return context;
}
